<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.texttechnologylab.ppr.blatt2</groupId>
    <artifactId>Blatt2</artifactId>
    <version>1.0</version>

    <organization>
        <name>Text technology Lab</name>
        <url>https://www.texttechnologylab.org</url>
    </organization>

    <developers>
        <developer>
            <name>Phalosa, Athalia</name>
            <email>s5902765@stud.uni-frankfurt.de</email>
            <url>https://ppr.gitlab.texttechnologylab.org/Athalia</url>
            <organization>Goethe University Frankfurt / PPR 2025</organization>
            <roles>
                <role>Student</role>
            </roles>
        </developer>

    </developers>


    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <version.json>20250517</version.json>
        <version.neo4j>2025.10.1</version.neo4j>
    </properties>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.json/json -->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${version.json}</version>
        </dependency>

        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j</artifactId>
            <version>${version.neo4j}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.neo4j/neo4j-common -->
        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j-common</artifactId>
            <version>${version.neo4j}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.neo4j/neo4j-cypher -->
        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j-cypher</artifactId>
            <version>${version.neo4j}</version>
        </dependency>
    </dependencies>

</project>
